default: &default
  adapter: postgresql
  encoding: unicode
  username: irtezahussain
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: managco_dev


# test:
#   <<: *default
#   database: managco_test

# production:
#   <<: *default
#   database: managco_production
#   username: managco
#   password: <%= ENV["MANAGCO_DATABASE_PASSWORD"] %>
